name: CI/CD to GKE with Artifact Registry

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build & Push Go image
        run: |
          COMMIT_SHA=${{ github.sha }}
          IMAGE_URI=${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdtest/go-app

          docker build -t $IMAGE_URI:latest -t $IMAGE_URI:$COMMIT_SHA ./go-app
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:$COMMIT_SHA

      - name: Build & Push Node image
        run: |
          COMMIT_SHA=${{ github.sha }}
          IMAGE_URI=${{ secrets.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicdtest/node-app

          docker build -t $IMAGE_URI:latest -t $IMAGE_URI:$COMMIT_SHA ./node-app
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:$COMMIT_SHA

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f manifests/go-deployment.yaml
          kubectl apply -f manifests/node-deployment.yaml
          # kubectl apply -f manifests/node-ingress.yaml
